name: Terraform Plan

on:
  - pull_request

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.2
        with:
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.4

      - name: Decrypt SOPS Secrets
        uses: rmb938/sops-decrypt-action@0.1.0
        with:
          secrets-directory: secrets

      - name: Start VPN
        run: |
          set -xe
          sudo apt-get install -y openvpn
          sudo cp secrets/decrypted/vpn-* /etc/openvpn/client/
          sudo systemctl start openvpn-client@vpn-config
          sleep 10
          route -n

      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform Plan
        run: |
          terraform plan -out=tf.plan

      - name: Stop VPN
        if: always()
        run: |
          set -xe
          sudo systemctl stop openvpn-client@vpn-config
